### PR TITLE
Adding Dockerfile

### PR DESCRIPTION
**Pull request by jeff-r-skillrev**
Hey @aestevens , take a look at this. It doesn't seem to work in the container for some reason. I also get the same error if I try to run your server locally. We can take a look at this together when we meet up. :)

(Nodemon may not be the best way to kick this off in Docker, since Docker is supposed to represent a production scenario. Maybe we could adjust the packge.json to have a way of starting the server as you want it ran in "production"?)

reeds$ docker run -it --name amp amplitube

> amplitube@1.0.0 server /app
> nodemon server/index.js

[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server/index.js`
module.js:549
    throw err;
    ^

Error: Cannot find module './dev'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/server/config/keys.js:4:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[nodemon] app crashed - waiting for file changes before starting...

### CODE REVIEW

**Comment by aestevens** [comment]
Hey @langboost, I realize I should have mentioned in my readme that you'll need your own `dev.js` inside the /server/config directory with a key for the YouTube data API to run the server locally. It's gitignore'd so you can't access the API key.

Specifically for this situation, though, I suspect that the logic in `/server/config/keys.js` is our issue here. This file is looking for an environment variable for Node, `NODE_ENV`, to be assigned the value `"production"` (by default it isn't) in order to use the production version of the Google API key (another environment variable); otherwise, it looks for the keys in dev.js. It looks like one way to address this is a `.npmrc` file at the project root with a single line: `production=true`, no quotations or anything.

This appears to be one way to run the server in production; however, there'd still be the issue of setting our production environment variables, including the API key and the port for the server. Can you setup environment variables as part of the build process with Docker?

**Comment by jeff-r-skillrev** [comment]
Thanks @aestevens . I added the logic for environment variables. It's industry standard to let Docker control these. There are some nice ways to control the values during deployment that I'll show you, although for constants that may never want to be changed by a devops team, you could certainly choose to put them in .npmrc as a dev. Anyway, if you could help me with a sample dev or prod.js file (in terms of structure and what the values look like), that would be helpful. I'd like to test this locally. I enabled api for my gmail acct. Just not sure what to do from there. Thanks!

**Comment by aestevens** [comment]
Cool @langboost, I see where you added the code for those variables. By comparison, I've only worked with Heroku for deployment, and it handles the NODE_ENV and PORT variables for you with Node builds; anything else you have to set yourself on Heroku's website using the dashboard for your app. Makes sense why Docker would handle them.

Now that you have an API key, you can use the structure of prod.js (just pushed it):
`module.exports = {
  googleAPIKey: process.env.GOOGLE_API_KEY
}`
 and replace the `process.env. ...` value with your API key for a dev.js file. That should allow for running locally at least. For running with Docker, I'm not sure!

**Comment by jeff-r-skillrev** [comment]
Well, it works now. Don't feel like you have to keep this. :) I am just trying to get a working example for when we meet up to discus Docker with the group. Now you can take a crack at hosting the front-end if you want. Once that works, we could put the two in a docker-compose.yml file together to really tie a bow on it.

**Pull request merged**
